<Window x:Class="WpfAppExceptionHandleStudy.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfAppExceptionHandleStudy"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center" Orientation="Vertical">
        <Button Width="150" Content="Throw" Click="ButtonBase_OnClick"/>
        <Button Width="150" Content="Async Throw with await" Click="ThrowExceptionAsync"/>
        <Button Width="150" Content="Async Throw without await" Click="ThrowExceptionAsyncWithoutAwait"/>
        <Button Width="150" Content="Throw with Thread start" Click="ThrowWithThreadStart"/>
    </StackPanel>
</Window>
